/*
Safepay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GenerateTimeBasedTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateTimeBasedTokenResponse{}

// GenerateTimeBasedTokenResponse struct for GenerateTimeBasedTokenResponse
type GenerateTimeBasedTokenResponse struct {
	Data *string `json:"data,omitempty"`
}

// NewGenerateTimeBasedTokenResponse instantiates a new GenerateTimeBasedTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateTimeBasedTokenResponse() *GenerateTimeBasedTokenResponse {
	this := GenerateTimeBasedTokenResponse{}
	return &this
}

// NewGenerateTimeBasedTokenResponseWithDefaults instantiates a new GenerateTimeBasedTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateTimeBasedTokenResponseWithDefaults() *GenerateTimeBasedTokenResponse {
	this := GenerateTimeBasedTokenResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GenerateTimeBasedTokenResponse) GetData() string {
	if o == nil || IsNil(o.Data) {
		var ret string
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateTimeBasedTokenResponse) GetDataOk() (*string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GenerateTimeBasedTokenResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given string and assigns it to the Data field.
func (o *GenerateTimeBasedTokenResponse) SetData(v string) {
	o.Data = &v
}

func (o GenerateTimeBasedTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateTimeBasedTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGenerateTimeBasedTokenResponse struct {
	value *GenerateTimeBasedTokenResponse
	isSet bool
}

func (v NullableGenerateTimeBasedTokenResponse) Get() *GenerateTimeBasedTokenResponse {
	return v.value
}

func (v *NullableGenerateTimeBasedTokenResponse) Set(val *GenerateTimeBasedTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateTimeBasedTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateTimeBasedTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateTimeBasedTokenResponse(val *GenerateTimeBasedTokenResponse) *NullableGenerateTimeBasedTokenResponse {
	return &NullableGenerateTimeBasedTokenResponse{value: val, isSet: true}
}

func (v NullableGenerateTimeBasedTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateTimeBasedTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


