/*
Safepay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateGuestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateGuestResponse{}

// CreateGuestResponse struct for CreateGuestResponse
type CreateGuestResponse struct {
	Data *CreateJWTResponseData `json:"data,omitempty"`
	Status *CreateJWTResponseStatus `json:"status,omitempty"`
}

// NewCreateGuestResponse instantiates a new CreateGuestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateGuestResponse() *CreateGuestResponse {
	this := CreateGuestResponse{}
	return &this
}

// NewCreateGuestResponseWithDefaults instantiates a new CreateGuestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateGuestResponseWithDefaults() *CreateGuestResponse {
	this := CreateGuestResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateGuestResponse) GetData() CreateJWTResponseData {
	if o == nil || IsNil(o.Data) {
		var ret CreateJWTResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGuestResponse) GetDataOk() (*CreateJWTResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateGuestResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateJWTResponseData and assigns it to the Data field.
func (o *CreateGuestResponse) SetData(v CreateJWTResponseData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateGuestResponse) GetStatus() CreateJWTResponseStatus {
	if o == nil || IsNil(o.Status) {
		var ret CreateJWTResponseStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateGuestResponse) GetStatusOk() (*CreateJWTResponseStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateGuestResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CreateJWTResponseStatus and assigns it to the Status field.
func (o *CreateGuestResponse) SetStatus(v CreateJWTResponseStatus) {
	o.Status = &v
}

func (o CreateGuestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateGuestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableCreateGuestResponse struct {
	value *CreateGuestResponse
	isSet bool
}

func (v NullableCreateGuestResponse) Get() *CreateGuestResponse {
	return v.value
}

func (v *NullableCreateGuestResponse) Set(val *CreateGuestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateGuestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateGuestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateGuestResponse(val *CreateGuestResponse) *NullableCreateGuestResponse {
	return &NullableCreateGuestResponse{value: val, isSet: true}
}

func (v NullableCreateGuestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateGuestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


