/*
Safepay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateJWTResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateJWTResponse{}

// CreateJWTResponse struct for CreateJWTResponse
type CreateJWTResponse struct {
	Data *CreateJWTResponseData `json:"data,omitempty"`
	Status *CreateJWTResponseStatus `json:"status,omitempty"`
}

// NewCreateJWTResponse instantiates a new CreateJWTResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateJWTResponse() *CreateJWTResponse {
	this := CreateJWTResponse{}
	return &this
}

// NewCreateJWTResponseWithDefaults instantiates a new CreateJWTResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateJWTResponseWithDefaults() *CreateJWTResponse {
	this := CreateJWTResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateJWTResponse) GetData() CreateJWTResponseData {
	if o == nil || IsNil(o.Data) {
		var ret CreateJWTResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJWTResponse) GetDataOk() (*CreateJWTResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateJWTResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateJWTResponseData and assigns it to the Data field.
func (o *CreateJWTResponse) SetData(v CreateJWTResponseData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateJWTResponse) GetStatus() CreateJWTResponseStatus {
	if o == nil || IsNil(o.Status) {
		var ret CreateJWTResponseStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateJWTResponse) GetStatusOk() (*CreateJWTResponseStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateJWTResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CreateJWTResponseStatus and assigns it to the Status field.
func (o *CreateJWTResponse) SetStatus(v CreateJWTResponseStatus) {
	o.Status = &v
}

func (o CreateJWTResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateJWTResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableCreateJWTResponse struct {
	value *CreateJWTResponse
	isSet bool
}

func (v NullableCreateJWTResponse) Get() *CreateJWTResponse {
	return v.value
}

func (v *NullableCreateJWTResponse) Set(val *CreateJWTResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateJWTResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateJWTResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateJWTResponse(val *CreateJWTResponse) *NullableCreateJWTResponse {
	return &NullableCreateJWTResponse{value: val, isSet: true}
}

func (v NullableCreateJWTResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateJWTResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


