/*
Safepay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateAPIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAPIKeyResponse{}

// CreateAPIKeyResponse struct for CreateAPIKeyResponse
type CreateAPIKeyResponse struct {
	Data *CreateAPIKeyResponseData `json:"data,omitempty"`
	Status *CreateJWTResponseStatus `json:"status,omitempty"`
}

// NewCreateAPIKeyResponse instantiates a new CreateAPIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAPIKeyResponse() *CreateAPIKeyResponse {
	this := CreateAPIKeyResponse{}
	return &this
}

// NewCreateAPIKeyResponseWithDefaults instantiates a new CreateAPIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAPIKeyResponseWithDefaults() *CreateAPIKeyResponse {
	this := CreateAPIKeyResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateAPIKeyResponse) GetData() CreateAPIKeyResponseData {
	if o == nil || IsNil(o.Data) {
		var ret CreateAPIKeyResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAPIKeyResponse) GetDataOk() (*CreateAPIKeyResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateAPIKeyResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateAPIKeyResponseData and assigns it to the Data field.
func (o *CreateAPIKeyResponse) SetData(v CreateAPIKeyResponseData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateAPIKeyResponse) GetStatus() CreateJWTResponseStatus {
	if o == nil || IsNil(o.Status) {
		var ret CreateJWTResponseStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAPIKeyResponse) GetStatusOk() (*CreateJWTResponseStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateAPIKeyResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given CreateJWTResponseStatus and assigns it to the Status field.
func (o *CreateAPIKeyResponse) SetStatus(v CreateJWTResponseStatus) {
	o.Status = &v
}

func (o CreateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAPIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableCreateAPIKeyResponse struct {
	value *CreateAPIKeyResponse
	isSet bool
}

func (v NullableCreateAPIKeyResponse) Get() *CreateAPIKeyResponse {
	return v.value
}

func (v *NullableCreateAPIKeyResponse) Set(val *CreateAPIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAPIKeyResponse(val *CreateAPIKeyResponse) *NullableCreateAPIKeyResponse {
	return &NullableCreateAPIKeyResponse{value: val, isSet: true}
}

func (v NullableCreateAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


